//
//  SANotificationConst.m
//  SuperApp
//
//  Created by VanJay on 2020/3/30.
//  Copyright © 2020 chaos network technology. All rights reserved.
//

#import "SANotificationConst.h"

NSNotificationName const kNotificationNameDeviceChanged = @"kNotificationNameDeviceChanged";
NSNotificationName const kNotificationNameReceiveRegistrationToken = @"kNotificationNameReceiveRegistrationToken";
NSNotificationName const kNotificationNameReceivedNewMessage = @"kNotificationNameReceivedNewMessage";
NSNotificationName const kNotificationNameSuccessGetAppHomeDynamicFunctionList = @"SuccessGetAppHomeDynamicFunctionList";
NSNotificationName const kNotificationNameSuccessGetAppTabBarConfigList = @"SuccessGetAppTabBarConfigList";
NSNotificationName const kNotificationNameSuccessGetDeliveryAppHomeDynamicFunctionList = @"kNotificationNameSuccessGetDeliveryAppHomeDynamicFunctionList";
NSNotificationName const kNotificationNameSuccessGetDeliveryAppTabBarConfigList = @"kNotificationNameSuccessGetDeliveryAppTabBarConfigList";
NSNotificationName const kNotificationNameUserChangedLocation = @"kNotificationNameUserChangedLocation";
NSNotificationName const kNotificationNameOrderSubmitSuccess = @"kNotificationNameOrderSubmitSuccess";
NSNotificationName const kNotificationNameLoginSuccess = @"kNotificationNameLoginSuccess";
NSNotificationName const kNotificationNameUserLogout = @"kNotificationNameUserLogout";
NSNotificationName const kNotificationNameSuccessGetTinhNowAppHomeDynamicFunctionList = @"kNotificationNameSuccessGetTinhNowAppHomeDynamicFunctionList";
NSNotificationName const kNotificationNameSuccessGetTinhNowAppTabBarConfigList = @"kNotificationNameSuccessGetTinhNowAppTabBarConfigList";
NSNotificationName const kNotificationNameSuccessGetGroupBuyAppTabBarConfigList = @"kNotificationNameSuccessGetGroupBuyAppTabBarConfigList";
NSNotificationName const kNotificationWechatPayOnResponse = @"kNotificationWechatPayOnResponse";
NSNotificationName const kNotificationNameUploadOfflineShoppingGoodsCompleted = @"kNotificationNameUploadOfflineShoppingGoodsCompleted";
NSNotificationName const kNotificationNameTNOrderSubmitSuccess = @"kNotificationNameTNOrderSubmitSuccess";
NSNotificationName const kNotificationNameTNOrderSubmited = @"kNotificationNameTNOrderSubmited";
NSNotificationName const kNotificationWechatAuthLoginResponse = @"kNotificationWechatAuthLoginResponse";
NSNotificationName const kNotificationNameReloadStoreDetail = @"kNotificationNameReloadStoreDetail";
NSNotificationName const kNotificationNameReloadStoreShoppingCart = @"kNotificationNameReloadStoreShoppingCart";
NSNotificationName const kNotificationNameRemoteConfigsUpdate = @"kNotificationNameRemoteConfigsUpdate";
NSNotificationName const kNotificationNameIMLoginSuccess = @"kNotificationNameIMLoginSuccess";
NSNotificationName const kNotificationNameVoipTokenChanged = @"kNotificationNameVoipTokenChanged";
NSNotificationName const kNotificationNameNewMessages = @"kNotificationNameNewMessages";
NSNotificationName const kNotificationNamePrinceBankResp = @"kNotificationNamePrinceBankResp";
NSNotificationName const kNotificationNameHuiOneResp = @"kNotificationNameHuiOneResp";
NSNotificationName const kNotificationNameDidReceiveHelloPlatformDeviceToken = @"kNotificationNameDidReceiveHelloPlatformDeviceToken";
NSNotificationName const kNotificationNamePushSMSLoginViewController = @"kNotificationNamePushSMSLoginViewController";
NSNotificationName const kNotificationNameSATabBarControllerChangeSelectedIndex = @"kNotificationNameSATabBarControllerChangeSelectedIndex";
